apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-productos-deployment
  labels:
    app: gestion-productos
spec:
  replicas: 3  # Número de réplicas para alta disponibilidad
  selector:
    matchLabels:
      app: gestion-productos
  template:
    metadata:
      labels:
        app: gestion-productos
    spec:
      containers:
        - name: gestion-productos
          image: robertofsocity/gestionproductos:latest  # Cambia a tu imagen de Docker
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Puedes cambiar el perfil según tus necesidades

---

apiVersion: v1
kind: Service
metadata:
  name: gestion-productos-service
spec:
  type: LoadBalancer  # Cambia a ClusterIP si es un servicio interno
  selector:
    app: gestion-productos
  ports:
    - protocol: TCP
      port: 8080        # Puerto accesible externamente
      targetPort: 8080  # Puerto del contenedor
